version: '3.9'

services:
  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    container_name: contact.pokemonit
    working_dir: /contact.pokemonit
    ports:
      - 3000:3000
    volumes:
      - .:/contact.pokemonit
      - ${HOME}/.ssh:/root/.ssh
    stdin_open: true
    tty: true
