version: '3.9'

volumes:
  node_modules:

services:
  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    container_name: contact.pokemonit
    working_dir: /contact.pokemonit
    ports:
      - 3000:3000
    volumes:
      - .:/contact.pokemonit
      - node_modules:/contact.pokemonit/node_modules
    environment:
      USER: 'docker'
    stdin_open: true
    tty: true
