export const COMPUTER_TITLE = '使われているPCの種類はなんですか？'
export const MICON_TITLE = 'Arduino Leonardo（マイコン）はブログ内で紹介しているものを使われていますか？'
export const LIBRARY_TITLE = '使われているライブラリはどちらですか？'
export const ARDUINO_TITLE = 'Arduino IDEのバージョンを教えてください'
export const AVR_BOARDS_TITLE = 'Arduino AVR Boardsのバージョンを教えてください'
export const WHERE_STOP_TITLE = 'どこで止まっていますか？'
export const DEBUG_TEXT_FIELD_TITLE = 'どこまでの動作を確認できているかを具体的に教えてください'
