import '../styles/globals.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import styled from '@emotion/styled'
import { AppBar, Toolbar, Typography } from '@mui/material'
import { RecoilRoot } from 'recoil'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>ポケモニット - 質問フォーム</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppBar position='static'>
        <Toolbar>
          <Typography variant='h6' noWrap component='div' sx={{ flexGrow: 1, display: { sm: 'block' } }}>
            ポケモニット - 質問フォーム
          </Typography>
        </Toolbar>
      </AppBar>
      <StyledContainer>
        <StyledMain>
          <RecoilRoot>
            <Component {...pageProps} />
          </RecoilRoot>
        </StyledMain>
      </StyledContainer>
    </>
  )
}

export default MyApp

const StyledContainer = styled.div`
  padding: 0 2rem;
`

const StyledMain = styled.main`
  display: flex;
  flex: 1;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 4rem 0;
`
