import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { AppBar, Toolbar, Typography } from '@mui/material'
import { RecoilRoot } from 'recoil'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>ポケモニット - 質問フォーム</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppBar position='static'>
        <Toolbar>
          <Typography variant='h6' noWrap component='div' sx={{ flexGrow: 1, display: { xs: 'none', sm: 'block' } }}>
            ポケモニット - 質問フォーム
          </Typography>
        </Toolbar>
      </AppBar>
      <RecoilRoot>
        <Component {...pageProps} />
      </RecoilRoot>
    </>
  )
}

export default MyApp
