import type { NextPage } from 'next'
import Head from 'next/head'
import { Radios } from '../components/Radios'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const formLabel = '質問の種類を教えて下さい。'
  const items = [
    { value: 'female', label: 'マイコンの導入方法について' },
    { value: 'male', label: 'コードがうまく動かない' },
    { value: 'other', label: 'その他' },
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>ポケモニット</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ポケモニット</h1>
        <Radios formLabel={formLabel} items={items} />
      </main>
    </div>
  )
}

export default Home
